### ISSUE TITLE
pow3

### ISSUE THREAD

**Issue by TuomLarsen** [anj1/AlgebraicNumbers.jl#1]
There's a TODO for efficient calculation of third power [here](https://github.com/anj1/AlgebraicNumbers.jl/blob/master/src/algebraic.jl#L162). Please would you be so kind and explain how (if at all) it is possible to make it more efficient than pow2 and *?

**Comment by anj1** [comment]
@TuomLarsen if you look at the implementation of pow2, you see that there is a 'shortcut' for computing x\*x that doesn't require us to compute the full polynomial resultant, like general multiplication does (the key lines here are 169 to 171, as of 72dac4efb9818dc0aafb10091bc096ba77bbf583). It is possible to extend this shortcut to x\*x\*x, but in that case I don't know how big the performance gain would be so it's not high on my list of priorities to do.

**Comment by TuomLarsen** [comment]
Thank you for the reply! Yes I saw pow2 but it is not clear to me how to extend the 'shortcut' to pow3, or general power. For pow2 it seems to take every second coefficient of x*negation-of-x, how would a scheme for pow3 look like?

**Comment by anj1** [comment]
A polynomial can be written as its decomposition in terms of roots: `p[x] = (x - r1)(x - r2)...`; all the code does is it constructs `(x^2 - r1^2)(x^2 - r2^2)...` and then considers the new polynomial you would obtain if you replaced `x^2` with `y`. 

Extending this trick to raising to the power of 3 would simply involve constructing `(x^3 - r1^3)(x^3 - r2^3)...` which can be done using the 3rd [roots of unity](https://en.wikipedia.org/wiki/Root_of_unity) instead of the 2nd roots of unity which are 1 and -1.

**Comment by anj1** [comment]
I'm going to close this issue as it seems to be about the mathematics of polynomials rather than the code itself.

**Comment by TuomLarsen** [comment]
Thank you! Please, one final question, if I may: does the computation of power of 3 involved complex numbers or is it possible to carry it out in integers only?

**Comment by TuomLarsen** [comment]
Thank you!

**Comment by anj1** [comment]
It involves complex numbers, specifically the field extension Q(w), where w is a 3rd unity of unity. But because this is a 'simple' field extension (the Galois group is isomorphic to the n=6 dihedral group), calculations can be done exactly without invoking the full machinery of algebraic numbers. So in theory it should be fairly efficient to carry out the calculation, especially for larger algebraic numbers, but I haven't actually crunched the numbers to see how much of an improvement it would have over computing the resultant.
